### ISSUE TITLE
檔案不齊全

### ISSUE THREAD

**Issue by m561247** [jqtangust/C0_MIPS32_64_Compiler#1]
對這個項目很有興趣，
不過檔案好像有缺，請問可以提供完整的檔案嗎？
謝謝！

**Comment by jqtangust** [comment]
感谢你的关注
我的详细设计思路可以在pdf中找到：https://github.com/jqtangust/C0_MIPS32_64_Compiler/blob/main/一种基于C0%20文法的MIPS32_64%20指令集下的编译器_唐家祺_2018302266.pdf

如有其他问题，您可以继续留言

**Comment by m561247** [comment]
缺 lex、error 的部分，您的意思是說看文檔即可嗎？ 謝謝！

**Comment by jqtangust** [comment]
非常感谢你的提示！我查看了头文件，确实有可能不太齐全
我现在还在休假，预计10天之后更新下这个项目

感谢你的关注！

**Comment by m561247** [comment]
請問還會更新嗎?
謝謝您!

**Comment by jqtangust** [comment]
感谢提醒
我会在近期更新

**Comment by jqtangust** [comment]
我已经提交了其他缺失的文件，感谢你的提醒

如果此项目还有其他问题，请让我知道，谢谢

**Comment by m561247** [comment]
感謝您的提交!
覺得這個項目很棒，謝謝!
